name: Build DLL on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: ls
    - name: Run tests
      run: cargo test --verbose
    - name: Rename DLL with tag
      run: |
        $tag = "${{ github.ref_name }}"
        Rename-Item "target\release\deno_windows_scm.dll" "deno_windows_scm_$tag.dll"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deno_windows_scm
        path: deno_windows_scm_${{ github.ref_name }}.dll
    
