name: Build DLL on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deno_windows_scm.dll
        path: target\release\deno_windows_scm.dll
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deno_windows_scm.pdb
        path: target\release\deno_windows_scm.pdb
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deno_windows_scm.dll.lib
        path: target\release\deno_windows_scm.dll.lib
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deno_windows_scm.dll.exp
        path: target\release\deno_windows_scm.dll.exp
    
